#!/bin/bash
echo "Installing Homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
clear

echo "Installing awscli, nodejs, python, ruby, cask, php-cs-fixer"
brew install awscli nodejs python ruby cask homebrew/php/php-cs-fixer

echo "Installing Compass"
sudo gem install compass compass-respond
clear


echo "Install nodemon, forever and grunt"
sudo npm install -g nodemon forever grunt grunt-cli
clear

echo "Install mysqlworkbench, virtualbox, google drive, dropbox, firefox, chrome, sublime text, atom, spotify, Grammarly"
brew cask install mysqlworkbench virtualbox virtualbox-extension-pack firefox google-chrome google-drive dropbox sublime-text atom grammarly spotify slack
clear

brew doctor

echo "Setup atom extensions"
apm install project-view project-manager atom-beautify

echo "Installing Oh My ZSH"
curl -L http://install.ohmyz.sh | sh
clear

echo "Install complete!"
