#!/bin/bash
echo "Install Xcode CLI"
sudo xcode-select --install
clear

echo "Installing Homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
clear

echo "Installing awscli, nodejs, python, ruby, cask"
brew install awscli nodejs python ruby cask

echo "Installing Compass"
sudo gem install compass
clear


echo "Install nodemon"
sudo npm install -g nodemon
clear 

echo "Install forever"
sudo npm install -g forever
clear

echo "Install grunt"
sudo npm install -g grunt grunt-cli
clear

echo "Install mysqlworkbench"
brew cask install mysqlworkbench
clear

echo "Install virtualbox"
brew cask install virtualbox
clear

brew doctor

echo "Installing Oh My ZSH"
curl -L http://install.ohmyz.sh | sh
clear

echo "Install complete!"