#!/bin/bash
echo "Installing Homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
clear

echo "Installing awscli, nodejs, python, ruby, cask"
brew install awscli nodejs python ruby cask

echo "Installing Compass"
sudo gem install compass
clear


echo "Install nodemon, forever and grunt"
sudo npm install -g nodemon forever grunt grunt-cli
clear

echo "Install mysqlworkbench, virtualbox, google drive, dropbox, firefox, chrome, sublime text, atom, Grammarly"
brew cask install mysqlworkbench virtualbox firefox google-chrome google-drive dropbox sublime-text atom grammarly
clear

brew doctor

echo "Installing Oh My ZSH"
curl -L http://install.ohmyz.sh | sh
clear

echo "Install complete!"
