# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
    #set the base box
    config.vm.box = 'ubuntu/xenial64'

    # provision the base box
    config.vm.provision 'shell', inline: 'export DEBIAN_FRONTEND=noninteractive; bash /vagrant/provision'
    config.vm.provision 'shell', inline: 'export DEBIAN_FRONTEND=noninteractive; service nginx start', run: "always"

    # forward the needed ports
    config.vm.network "private_network", ip: "192.168.100.100"

    config.vm.provider :virtualbox do |vb|
      vb.name = "Danger Room - 16.04"
    end


    # Share your sites directory
    config.vm.synced_folder '/Users/tcmccarthy/Sites', '/www', mount_options: ["dmode=775,fmode=664"]
end
