#!/bin/bash

wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'

sudo apt-get -yq update

sudo apt-get install -y atom build-essential dkms linux-headers-$(uname -r) virtualbox-guest-additions-iso virtualbox-guest-dkms virtualbox-guest-x11

sudo npm i -g grunt grunt-cli pm2

sudo chown -R $(whoami):$(whoami) ~

rm ~/.bash_login
