#!/bin/bash

wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'

sudo apt-get -yq update

sudo apt-get install -y atom

sudo npm i -g grunt grunt-cli pm2

rm ~/.bash_login
