#!/bin/bash

## Install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

## Setup brew cask
brew install cask

## Setup vagrant and virtualbox
brew cask install virtualbox virtualbox-extension-pack vagrant
