# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider :virtualbox do |vb|
    vb.name = "Dev Sandbox 18.04 - PHP7"
    vb.memory = 4096
    vb.gui = true
    vb.customize ["setextradata", :id, "VBoxInternal2/EfiGraphicsResolution", "1920x1080"]
  end

  config.vm.network "private_network", ip: "192.168.100.250"

  config.vm.provision "shell", inline: "export DEBIAN_FRONTEND=noninteractive; ln -sf /vagrant/provision /home/vagrant/.bash_login"
end
