#!/bin/bash

#### CONFIGURES IP TABLES FOR UBUNTU WEBSERVER #####

## FLUSH ALL RULES
iptables -F

## TURN ON LOOP BACK
iptables -I INPUT 1 -i lo -j ACCEPT

## ALLOW ALL INPUT (THIS IS THE DEFAULT POLICY, THE DROP WILL COME LATER. WE SET IT THIS WAY IN CASE A MISTAKE HAPPENS AND WE LOCK OURSELVES OUT)
iptables -P INPUT ACCEPT

## LOAD SUPPORT FOR ROUTINE
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

## OPEN PORTS FOR BASIC WEB OPS
iptables -A INPUT -i eth1 -p all -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -A INPUT -p tcp --dport 11211 -j ACCEPT
iptables -A INPUT -p tcp --dport 3306 -j ACCEPT

## EMAIL PORTS, IGNORED BY DEFAULT
#iptables -A INPUT -p tcp --dport 25 -j ACCEPT
#iptables -A INPUT -p tcp --dport 465 -j ACCEPT
#iptables -A INPUT -p tcp -m tcp --dport 110 -j ACCEPT
#iptables -A INPUT -p tcp -m tcp --dport 995 -j ACCEPT
#iptables -A INPUT -p tcp -m tcp --dport 143 -j ACCEPT
#iptables -A INPUT -p tcp -m tcp --dport 993 -j ACCEPT

## ADDED SECURITY FOR ANTI DDOS
iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP
iptables -A INPUT -f -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

## DROP ANY PACKETS NOT COVERED BY INPUT POLICY
iptables -A INPUT -j DROP

## ALLOW PACKETS FOR ALL OTHER DIRECTIONS
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

## SAVE OUR POLICY AND MAKE PERSIST BY INSTALLING IPTABLES-PERSISTENT
apt-get -y update
apt-get install -y iptables-persistent
sudo netfilter-persistent save
