#!/bin/bash

curl -sL https://deb.nodesource.com/setup_8.x | bash

## primary ubuntu setup
curl https://raw.githubusercontent.com/tc-mccarthy/dev/master/webserver/ubuntu-setup/16.04/ubuntuKickStart-app.sh | bash

## install pm2
npm install -g pm2

## load config files
#cp /vagrant/config_files/mysqld.cnf /etc/mysql/mysql.conf.d/.
cp /vagrant/config_files/memcached.conf /etc/.

rm -Rf /etc/nginx/sites-enabled
rm /etc/nginx/nginx.conf
rm /etc/nginx/fastcgi_params
ln -sf /www/mccarthy_digital_config/nginx/sites-enabled /etc/nginx/.
ln -sf /www/mccarthy_digital_config/nginx/journodev_list /etc/nginx/.
ln -sf /www/mccarthy_digital_config/ssl /etc/nginx/.
ln -sf /www/dev/webserver/nginx/global /etc/nginx/.
ln -sf /www/dev/webserver/nginx/nginx.conf /etc/nginx/.
ln -sf /www/dev/webserver/nginx/fastcgi_params /etc/nginx/.

## create log directories
mkdir -p /var/log/nodejs

## adds nginx user to ubuntu
usermod -aG vagrant www-data

## add host
echo "192.168.100.101 localhost" >> /etc/hosts

## add root user
# mysql -e "create user 'root'@'%' IDENTIFIED BY 'root'; grant all on *.* to 'root'@'%';"

## restart service stack
service mysql restart
service memcached restart
nginx -t && nginx -s reload

mysql < /vagrant/config_files/mysql_user_setup.sql
