# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
    #set the base box
    config.vm.box = "opensky/windows-7-professional-sp1-x64"
    config.vm.box_version = "0.1.0"

    # forward the needed ports
    config.vm.network "private_network", ip: "192.168.100.110"

    config.vm.provider :virtualbox do |vb|
      vb.name = "Windows 7 Sandbox"
    end


    # Share your sites directory
    config.vm.synced_folder ENV["HOME"], '/host_home', mount_options: ["dmode=775,fmode=664"]
end
