#!/bin/bash

#### CONFIGURES IP TABLES FOR UBUNTU WEBSERVER #####

## FLUSH ALL RULES
sudo iptables -F

## TURN ON LOOP BACK
sudo iptables -I INPUT 1 -i lo -j ACCEPT

## ALLOW ALL INPUT (THIS IS THE DEFAULT POLICY, THE DROP WILL COME LATER. WE SET IT THIS WAY IN CASE A MISTAKE HAPPENS AND WE LOCK OURSELVES OUT)
sudo iptables -P INPUT ACCEPT

## LOAD SUPPORT FOR ROUTINE
sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

## OPEN PORTS FOR BASIC WEB OPS
sudo iptables -A INPUT -i eth1 -p all -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 11211 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 3306 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 27017 -j ACCEPT

## ADDED SECURITY FOR ANTI DDOS
sudo iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP
sudo iptables -A INPUT -f -j DROP
sudo iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP
sudo iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

## DROP ANY PACKETS NOT COVERED BY INPUT POLICY
sudo iptables -A INPUT -j DROP

## ALLOW PACKETS FOR ALL OTHER DIRECTIONS
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT

## SAVE OUR POLICY AND MAKE PERSIST BY INSTALLING sudo iptables-PERSISTENT
sudo apt-get -y update
sudo apt-get install -y sudo iptables-persistent
sudo netfilter-persistent save
