#!/bin/bash

## create nginx directory
mkdir -p ~/nginx

## switch to nginx directory
cd ~/nginx

## set up basic dependencies
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get install -y build-essential git tree unzip htop libssl-dev

## install pcre
cd ~/nginx
mkdir -p pcre
curl https://ftp.pcre.org/pub/pcre/pcre-8.43.tar.bz2 | tar jxf - --strip-components 1 -C ./pcre
cd ./pcre
./configure
make
sudo make install

## set up zlib for gzip
cd ~/nginx
mkdir -p ./zlib
curl http://zlib.net/zlib-1.2.11.tar.gz | tar zxf - --strip-components 1 -C ./zlib
cd ./zlib
./configure
make
sudo make install

## get purge module
cd ~/nginx
git clone https://github.com/FRiCKLE/ngx_cache_purge.git
cd ./ngx_cache_purge

## setup nginx
cd ~/nginx
mkdir -p nginx
curl https://nginx.org/download/nginx-1.14.2.tar.gz | tar zxf - --strip-components 1 -C ./nginx
cd ./nginx

./configure --user=nginx \
            --group=nginx \
            --prefix=/etc/nginx \
            --sbin-path=/usr/sbin/nginx \
            --conf-path=/etc/nginx/nginx.conf \
            --pid-path=/var/run/nginx.pid \
            --lock-path=/var/run/nginx.lock \
            --error-log-path=/var/log/nginx/error.log \
            --http-log-path=/var/log/nginx/access.log \
            --with-http_gzip_static_module \
            --with-http_stub_status_module \
            --with-http_ssl_module \
            --with-pcre=../pcre \
            --with-zlib=../zlib \
            --with-file-aio \
            --with-http_realip_module \
            --with-stream \
            --without-http_scgi_module \
            --without-http_uwsgi_module \
            --with-http_realip_module \
            --add-module=../ngx_cache_purge
make
sudo make install

sudo ln -sf /www/mccarthy_digital_config/nginx/* /etc/nginx/.
sudo nginx
