#!/bin/bash

sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get -y update
sudo apt-get install -y php7.3 \
                        php7.3-cli \
                        php7.3-common \
                        php7.3-json \
                        php7.3-curl \
                        php-mysql \
                        php7.3-mbstring \
                        php7.3-zip \
                        php7.3-fpm \
                        php7.3-xml \
                        php-memcached
